%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Convert PNG images to AVI movies
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function png2avi(pngPATHpart, nSnapshot, framerate, sysParam)

% Get the directory and file names for the movies
[movieDIR,bodyFN] = fileparts(strcat(pngPATHpart,'.pdb'));

% Generate VideoMach scripts to convert images to movies
project1 = sprintf('%s_view1.vmp', pngPATHpart);
project2 = sprintf('%s_view2.vmp', pngPATHpart);
project3 = sprintf('%s_view3.vmp', pngPATHpart);
fid1 = fopen(project1,'w');
fid2 = fopen(project2,'w');
fid3 = fopen(project3,'w');
writeVideoMachProject(fid1,movieDIR,sprintf('%s_view1',bodyFN),nSnapshot,'avi',framerate,sysParam);
writeVideoMachProject(fid2,movieDIR,sprintf('%s_view2',bodyFN),nSnapshot,'avi',framerate,sysParam);
writeVideoMachProject(fid3,movieDIR,sprintf('%s_view3',bodyFN),nSnapshot,'avi',framerate,sysParam);
fclose(fid1);
fclose(fid2);
fclose(fid3);

% Run VideoMach
runVideoMach1 = sprintf('%s /openproject="%s" /start /exit', sysParam.videomachEXE, project1);
runVideoMach2 = sprintf('%s /openproject="%s" /start /exit', sysParam.videomachEXE, project2);
runVideoMach3 = sprintf('%s /openproject="%s" /start /exit', sysParam.videomachEXE, project3);
system(runVideoMach1);
system(runVideoMach2);
system(runVideoMach3);

end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Generate a VideoMach project file
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [] = writeVideoMachProject(fid,movieDIR,bodyFN,nSnapshot,outputFormat,framerate,param)
%framerate = param.framerate;
%colorbarFN = param.colorbarFN;
logoFN = param.logoFN;
% writing header
fprintf(fid,'<Header>\n');
fprintf(fid,'	<BlockVersion type="int">314</>\n');
fprintf(fid,'	<Id type="string">VideoMach#20Project</>\n');
fprintf(fid,'	<Creator type="string">VideoMach#205.8.3</>\n');
fprintf(fid,'</Header>\n');
% writing file list
fprintf(fid,'<FileList>\n');
fprintf(fid,'	<Video>\n');
fprintf(fid,'		<BlockVersion type="int">314</>\n');
for i=0:nSnapshot
    fprintf(fid,'		<Item%d>\n',i+1);
    fprintf(fid,'			<UniqueId type="int">%d</>\n',i);
    fprintf(fid,'			<FileName type="string">%s_%03d.png</>\n',fullfile(movieDIR,bodyFN),i);
    fprintf(fid,'			<StartQuant type="int">0</>\n');
    fprintf(fid,'			<EndQuant type="int">0</>\n');
    fprintf(fid,'			<MaxQuants type="int">1</>\n');
    fprintf(fid,'			<FrameRate type="float">%d</>\n',framerate);
    fprintf(fid,'			<ReadFwd type="bool">T</>\n');
    fprintf(fid,'			<LinkId type="int">2147483647</>\n');
    fprintf(fid,'		</Item%d>\n',i+1);
end
fprintf(fid,'	</Video>\n');
fprintf(fid,'</FileList>\n');
fprintf(fid,'<OpticFilters>\n');
fprintf(fid,'	<BlockVersion type="int">314</>\n');
% fprintf(fid,'	<Item1>\n');
% fprintf(fid,'		<Id type="string">Overlay</>\n');
% fprintf(fid,'		<Data1>\n');
% fprintf(fid,'			<FileName type="string">%s</>\n',colorbarFN);
% fprintf(fid,'			<SeqMode type="int">1024</>\n');
% fprintf(fid,'			<Corner type="int">1634497125</>\n');
% fprintf(fid,'			<OffsX type="int">400</>\n');
% fprintf(fid,'			<OffsY type="int">400</>\n');
% fprintf(fid,'			<LoopMode type="int">1</>\n');
% fprintf(fid,'			<LoopCount type="int">0</>\n');
% fprintf(fid,'			<TranspMode type="int">2</>\n');
% fprintf(fid,'			<TranspColor type="int">0</>\n');
% fprintf(fid,'			<AntiAliasing type="bool">T</>\n');
% fprintf(fid,'		</Data1>\n');
% fprintf(fid,'	</Item1>\n');
% fprintf(fid,'	<Item2>\n');
% fprintf(fid,'		<Id type="string">AddText</>\n');
% fprintf(fid,'		<Data1>\n');
% fprintf(fid,'			<FontName type="string">Arial</>\n');
% fprintf(fid,'			<FontHeight type="int">25</>\n');
% fprintf(fid,'			<CharSet type="word">1</>\n');
% fprintf(fid,'			<TextColor type="int">16777215</>\n');
% fprintf(fid,'			<FontBold type="bool">F</>\n');
% fprintf(fid,'			<FontItalic type="bool">F</>\n');
% fprintf(fid,'			<FontUnderline type="bool">F</>\n');
% fprintf(fid,'			<FontStrikeout type="bool">F</>\n');
% fprintf(fid,'			<CharAngle type="float">0</>\n');
% fprintf(fid,'			<TextAngle type="float">0</>\n');
% fprintf(fid,'			<ShadowEnabled type="bool">T</>\n');
% fprintf(fid,'			<ShadowColor type="int">0</>\n');
% fprintf(fid,'			<ShadowBlur type="int">2</>\n');
% fprintf(fid,'			<ShadowOpacity type="int">100</>\n');
% fprintf(fid,'			<ShadowOffsetX type="int">2</>\n');
% fprintf(fid,'			<ShadowOffsetY type="int">2</>\n');
% fprintf(fid,'			<TextString type="string">%1.1f</>\n',minRMSFnm);
% fprintf(fid,'			<XPos type="int">360</>\n');
% fprintf(fid,'			<YPos type="int">445</>\n');
% fprintf(fid,'			<TimeOffset type="float">0</>\n');
% fprintf(fid,'			<TimeScale type="float">1</>\n');
% fprintf(fid,'			<GUISameFont type="bool">T</>\n');
% fprintf(fid,'		</Data1>\n');
% fprintf(fid,'	</Item2>\n');
% fprintf(fid,'	<Item3>\n');
% fprintf(fid,'		<Id type="string">AddText</>\n');
% fprintf(fid,'		<Data1>\n');
% fprintf(fid,'			<FontName type="string">Arial</>\n');
% fprintf(fid,'			<FontHeight type="int">25</>\n');
% fprintf(fid,'			<CharSet type="word">1</>\n');
% fprintf(fid,'			<TextColor type="int">16777215</>\n');
% fprintf(fid,'			<FontBold type="bool">F</>\n');
% fprintf(fid,'			<FontItalic type="bool">F</>\n');
% fprintf(fid,'			<FontUnderline type="bool">F</>\n');
% fprintf(fid,'			<FontStrikeout type="bool">F</>\n');
% fprintf(fid,'			<CharAngle type="float">0</>\n');
% fprintf(fid,'			<TextAngle type="float">0</>\n');
% fprintf(fid,'			<ShadowEnabled type="bool">T</>\n');
% fprintf(fid,'			<ShadowColor type="int">0</>\n');
% fprintf(fid,'			<ShadowBlur type="int">2</>\n');
% fprintf(fid,'			<ShadowOpacity type="int">100</>\n');
% fprintf(fid,'			<ShadowOffsetX type="int">2</>\n');
% fprintf(fid,'			<ShadowOffsetY type="int">2</>\n');
% fprintf(fid,'			<TextString type="string">#3E%1.1f#20nm</>\n',maxRMSFnm);
% fprintf(fid,'			<XPos type="int">560</>\n');
% fprintf(fid,'			<YPos type="int">445</>\n');
% fprintf(fid,'			<TimeOffset type="float">0</>\n');
% fprintf(fid,'			<TimeScale type="float">1</>\n');
% fprintf(fid,'			<GUISameFont type="bool">T</>\n');
% fprintf(fid,'		</Data1>\n');
% fprintf(fid,'	</Item3>\n');
fprintf(fid,'	<Item4>\n');
fprintf(fid,'		<Id type="string">Overlay</>\n');
fprintf(fid,'		<Data1>\n');
fprintf(fid,'			<FileName type="string">%s</>\n',logoFN);
fprintf(fid,'			<SeqMode type="int">1024</>\n');
fprintf(fid,'			<Corner type="int">88</>\n');
fprintf(fid,'			<OffsX type="int">0</>\n');
fprintf(fid,'			<OffsY type="int">400</>\n');
fprintf(fid,'			<LoopMode type="int">1</>\n');
fprintf(fid,'			<LoopCount type="int">0</>\n');
fprintf(fid,'			<TranspMode type="int">0</>\n');
fprintf(fid,'			<TranspColor type="int">15395562</>\n');
fprintf(fid,'			<AntiAliasing type="bool">T</>\n');
fprintf(fid,'		</Data1>\n');
fprintf(fid,'	</Item4>\n');
fprintf(fid,'	<Item5>\n');
fprintf(fid,'		<Id type="string">AddText</>\n');
fprintf(fid,'		<Data1>\n');
fprintf(fid,'			<FontName type="string">Arial</>\n');
fprintf(fid,'			<FontHeight type="int">22</>\n');
fprintf(fid,'			<CharSet type="word">1</>\n');
fprintf(fid,'			<TextColor type="int">16777215</>\n');
fprintf(fid,'			<FontBold type="bool">F</>\n');
fprintf(fid,'			<FontItalic type="bool">F</>\n');
fprintf(fid,'			<FontUnderline type="bool">F</>\n');
fprintf(fid,'			<FontStrikeout type="bool">F</>\n');
fprintf(fid,'			<CharAngle type="float">0</>\n');
fprintf(fid,'			<TextAngle type="float">0</>\n');
fprintf(fid,'			<ShadowEnabled type="bool">T</>\n');
fprintf(fid,'			<ShadowColor type="int">0</>\n');
fprintf(fid,'			<ShadowBlur type="int">1</>\n');
fprintf(fid,'			<ShadowOpacity type="int">100</>\n');
fprintf(fid,'			<ShadowOffsetX type="int">2</>\n');
fprintf(fid,'			<ShadowOffsetY type="int">2</>\n');
fprintf(fid,'			<TextString type="string">http://cando-dna-origami.org</>\n');
fprintf(fid,'			<XPos type="int">50</>\n');
fprintf(fid,'			<YPos type="int">450</>\n');
fprintf(fid,'			<TimeOffset type="float">0</>\n');
fprintf(fid,'			<TimeScale type="float">1</>\n');
fprintf(fid,'			<GUISameFont type="bool">T</>\n');
fprintf(fid,'		</Data1>\n');
fprintf(fid,'	</Item5>\n');
fprintf(fid,'</OpticFilters>\n');
% writing output format
if strcmp(outputFormat,'avi')
    fprintf(fid,'<OutputSettings>\n');
    fprintf(fid,'	<Common>\n');   
    fprintf(fid,'		<BlockVersion type="int">314</>\n');
    fprintf(fid,'		<OutputMode type="int">0</>\n');
    fprintf(fid,'		<SplitSize type="float">2147483648</>\n');
    fprintf(fid,'		<SaveInfo>\n');
    fprintf(fid,'			<Version type="word">2</>\n');
    fprintf(fid,'			<ffComments>\n');
    fprintf(fid,'			</ffComments>\n');
    fprintf(fid,'		</SaveInfo>\n');
    fprintf(fid,'	</Common>\n');
    fprintf(fid,'	<Video>\n');
    fprintf(fid,'		<BlockVersion type="int">500</>\n');
    fprintf(fid,'		<FileName type="string">%s.avi</>\n',fullfile(movieDIR,strcat(bodyFN)));
    fprintf(fid,'		<FrameRateCustom type="bool">F</>\n');
    fprintf(fid,'		<FrameRate type="float">10</>\n');
    fprintf(fid,'		<KeepDuration type="bool">T</>\n');
    fprintf(fid,'		<ColorDepthCustom type="bool">F</>\n');
    fprintf(fid,'		<ColorDepth type="int">24</>\n');
    fprintf(fid,'		<SinglePalette type="bool">T</>\n');
    fprintf(fid,'		<Dithering type="int">2</>\n');
    fprintf(fid,'		<GrayScale type="bool">F</>\n');
    fprintf(fid,'		<ResizeCustom type="bool">F</>\n');
    fprintf(fid,'		<ResizeFolder>\n');
    fprintf(fid,'			<ResX type="int">0</>\n');
    fprintf(fid,'			<ResY type="int">0</>\n');
    fprintf(fid,'			<Bilinear type="bool">T</>\n');
    fprintf(fid,'			<EnlargeMode type="int">0</>\n');
    fprintf(fid,'			<ShrinkMode type="int">0</>\n');
    fprintf(fid,'			<BorderColor type="int">0</>\n');
    fprintf(fid,'		</ResizeFolder>\n');
    fprintf(fid,'		<PrintResCustom type="bool">F</>\n');
    fprintf(fid,'		<PrintResX type="int">0</>\n');
    fprintf(fid,'		<PrintResY type="int">0</>\n');
    fprintf(fid,'		<VideoFormatInfo type="string">Cinepak#20Codec#20by#20Radius</>\n');
    fprintf(fid,'		<FileFormatIndex type="int">5</>\n');
    fprintf(fid,'		<FileFormatFolder>\n');
    fprintf(fid,'			<vFileFmtId type="int">6</>\n');
    fprintf(fid,'			<vCodecId type="int">1684633187</>\n');
    fprintf(fid,'			<vCodecDataSize type="int">0</>\n');
    fprintf(fid,'			<vFPS type="float">10</>\n');
    fprintf(fid,'			<vKeepDuration type="bool">T</>\n');
    fprintf(fid,'			<vBitRate type="int">0</>\n');
    fprintf(fid,'			<vBitRateMax type="int">0</>\n');
    fprintf(fid,'			<vBitRateMin type="int">0</>\n');
    fprintf(fid,'			<vKeyFrameRate type="int">0</>\n');
    fprintf(fid,'			<vQuality type="float">100</>\n');
    fprintf(fid,'			<vAsr type="int">0</>\n');
    fprintf(fid,'			<vDpiX type="int">0</>\n');
    fprintf(fid,'			<vDpiY type="int">0</>\n');
    fprintf(fid,'			<vOutResX type="int">640</>\n');
    fprintf(fid,'			<vOutResY type="int">480</>\n');
    fprintf(fid,'			<vOutBpp type="int">24</>\n');
    fprintf(fid,'			<vCodecName type="string">Cinepak#20Codec#20by#20Radius</>\n');
    fprintf(fid,'		</FileFormatFolder>\n');
    fprintf(fid,'	</Video>\n');
    fprintf(fid,'	<Audio>\n');
    fprintf(fid,'		<BlockVersion type="int">500</>\n');
    fprintf(fid,'		<FileName type="string">%s.avi</>\n',fullfile(movieDIR,bodyFN));
    fprintf(fid,'		<SampleRateCustom type="bool">F</>\n');
    fprintf(fid,'		<SampleRate type="word">44100</>\n');
    fprintf(fid,'		<ChannelsCustom type="bool">F</>\n');
    fprintf(fid,'		<Channels type="word">2</>\n');
    fprintf(fid,'		<SampleResCustom type="bool">F</>\n');
    fprintf(fid,'		<SampleRes type="word">16</>\n');
    fprintf(fid,'		<AudioFormatInfo type="string">PCM,#20uncompressed</>\n');
    fprintf(fid,'		<FileFormatIndex type="int">0</>\n');
    fprintf(fid,'		<FileFormatFolder>\n');
    fprintf(fid,'			<aFileFmtId type="int">6</>\n');
    fprintf(fid,'			<aCodecId type="word">1</>\n');
    fprintf(fid,'			<aWaveFmtOut type="bin" size="18">0100020044AC000010B10200040010000000</>\n');
    fprintf(fid,'			<aBitRate type="word">0</>\n');
    fprintf(fid,'			<aQuality type="float">0</>\n');
    fprintf(fid,'			<aCodecName type="string">PCM,#20uncompressed</>\n');
    fprintf(fid,'		</FileFormatFolder>\n');
    fprintf(fid,'	</Audio>\n');
    fprintf(fid,'</OutputSettings>    \n');
elseif strcmp(outputFormat,'png')
    fprintf(fid,'<OutputSettings>n');
    fprintf(fid,'	<Common>n');
    fprintf(fid,'		<BlockVersion type="int">314</>n');
    fprintf(fid,'		<OutputMode type="int">0</>n');
    fprintf(fid,'		<SplitSize type="float">1099511627776000000</>n');
    fprintf(fid,'		<SaveInfo>n');
    fprintf(fid,'			<Version type="word">2</>n');
    fprintf(fid,'			<ffComments>n');
    fprintf(fid,'			</ffComments>n');
    fprintf(fid,'		</SaveInfo>n');
    fprintf(fid,'	</Common>n');
    fprintf(fid,'	<Video>n');
    fprintf(fid,'		<BlockVersion type="int">500</>n');
    fprintf(fid,'		<FileName type="string">%s_averaged.png</>n',fullfile(movieDIR,bodyFN));
    fprintf(fid,'		<FrameRateCustom type="bool">T</>n');
    fprintf(fid,'		<FrameRate type="float">10</>n');
    fprintf(fid,'		<KeepDuration type="bool">F</>n');
    fprintf(fid,'		<ColorDepthCustom type="bool">F</>n');
    fprintf(fid,'		<ColorDepth type="int">24</>n');
    fprintf(fid,'		<SinglePalette type="bool">T</>n');
    fprintf(fid,'		<Dithering type="int">2</>n');
    fprintf(fid,'		<GrayScale type="bool">F</>n');
    fprintf(fid,'		<ResizeCustom type="bool">F</>n');
    fprintf(fid,'		<ResizeFolder>n');
    fprintf(fid,'			<ResX type="int">0</>n');
    fprintf(fid,'			<ResY type="int">0</>n');
    fprintf(fid,'			<Bilinear type="bool">T</>n');
    fprintf(fid,'			<EnlargeMode type="int">0</>n');
    fprintf(fid,'			<ShrinkMode type="int">0</>n');
    fprintf(fid,'			<BorderColor type="int">0</>n');
    fprintf(fid,'		</ResizeFolder>n');
    fprintf(fid,'		<PrintResCustom type="bool">F</>n');
    fprintf(fid,'		<PrintResX type="int">0</>n');
    fprintf(fid,'		<PrintResY type="int">0</>n');
    fprintf(fid,'		<VideoFormatInfo type="string">PNG#20Compression#20Level:#207#20of#209</>n');
    fprintf(fid,'		<FileFormatIndex type="int">8</>n');
    fprintf(fid,'		<FileFormatFolder>n');
    fprintf(fid,'			<vFileFmtId type="int">9</>n');
    fprintf(fid,'			<vCodecId type="int">7</>n');
    fprintf(fid,'			<vCodecDataSize type="int">0</>n');
    fprintf(fid,'			<vFPS type="float">10</>n');
    fprintf(fid,'			<vKeepDuration type="bool">F</>n');
    fprintf(fid,'			<vBitRate type="int">0</>n');
    fprintf(fid,'			<vBitRateMax type="int">0</>n');
    fprintf(fid,'			<vBitRateMin type="int">0</>n');
    fprintf(fid,'			<vKeyFrameRate type="int">0</>n');
    fprintf(fid,'			<vQuality type="float">0</>n');
    fprintf(fid,'			<vAsr type="int">0</>n');
    fprintf(fid,'			<vDpiX type="int">0</>n');
    fprintf(fid,'			<vDpiY type="int">0</>n');
    fprintf(fid,'			<vOutResX type="int">640</>n');
    fprintf(fid,'			<vOutResY type="int">480</>n');
    fprintf(fid,'			<vOutBpp type="int">24</>n');
    fprintf(fid,'			<vCodecName type="string">PNG#20Compression#20Level:#207#20of#209</>n');
    fprintf(fid,'		</FileFormatFolder>n');
    fprintf(fid,'	</Video>n');
    fprintf(fid,'	<Audio>n');
    fprintf(fid,'		<BlockVersion type="int">500</>n');
    fprintf(fid,'		<FileName type="string">%s_averaged.png</>n',fullfile(movieDIR,bodyFN));
    fprintf(fid,'		<SampleRateCustom type="bool">F</>n');
    fprintf(fid,'		<SampleRate type="word">44100</>n');
    fprintf(fid,'		<ChannelsCustom type="bool">F</>n');
    fprintf(fid,'		<Channels type="word">2</>n');
    fprintf(fid,'		<SampleResCustom type="bool">F</>n');
    fprintf(fid,'		<SampleRes type="word">16</>n');
    fprintf(fid,'	</Audio>n');
    fprintf(fid,'</OutputSettings>\n');
elseif strcmp(outputFormat,'gif')
    fprintf(fid,'<OutputSettings>\n');
    fprintf(fid,'	<Common>\n');   
    fprintf(fid,'		<BlockVersion type="int">314</>\n');
    fprintf(fid,'		<OutputMode type="int">0</>\n');
    fprintf(fid,'		<SplitSize type="float">2147483648</>\n');
    fprintf(fid,'		<SaveInfo>\n');
    fprintf(fid,'			<Version type="word">2</>\n');
    fprintf(fid,'			<ffComments>\n');
    fprintf(fid,'			</ffComments>\n');
    fprintf(fid,'		</SaveInfo>\n');
    fprintf(fid,'	</Common>\n');
    fprintf(fid,'	<Video>\n');
    fprintf(fid,'		<BlockVersion type="int">500</>\n');
    fprintf(fid,'		<FileName type="string">%s.gif</>\n',fullfile(movieDIR,strcat('fluctuation',bodyFN)));
    fprintf(fid,'		<FrameRateCustom type="bool">F</>\n');
    fprintf(fid,'		<FrameRate type="float">10</>\n');
    fprintf(fid,'		<KeepDuration type="bool">T</>\n');
    fprintf(fid,'		<ColorDepthCustom type="bool">F</>\n');
    fprintf(fid,'		<ColorDepth type="int">24</>\n');
    fprintf(fid,'		<SinglePalette type="bool">T</>\n');
    fprintf(fid,'		<Dithering type="int">2</>\n');
    fprintf(fid,'		<GrayScale type="bool">F</>\n');
    fprintf(fid,'		<ResizeCustom type="bool">F</>\n');
    fprintf(fid,'		<ResizeFolder>\n');
    fprintf(fid,'			<ResX type="int">0</>\n');
    fprintf(fid,'			<ResY type="int">0</>\n');
    fprintf(fid,'			<Bilinear type="bool">T</>\n');
    fprintf(fid,'			<EnlargeMode type="int">0</>\n');
    fprintf(fid,'			<ShrinkMode type="int">0</>\n');
    fprintf(fid,'			<BorderColor type="int">0</>\n');
    fprintf(fid,'		</ResizeFolder>\n');
    fprintf(fid,'		<PrintResCustom type="bool">F</>\n');
    fprintf(fid,'		<PrintResX type="int">0</>\n');
    fprintf(fid,'		<PrintResY type="int">0</>\n');
    fprintf(fid,'		<VideoFormatInfo type="string">Cinepak#20Codec#20by#20Radius</>\n');
    fprintf(fid,'		<FileFormatIndex type="int">5</>\n');
    fprintf(fid,'		<FileFormatFolder>\n');
    fprintf(fid,'			<vFileFmtId type="int">6</>\n');
    fprintf(fid,'			<vCodecId type="int">1684633187</>\n');
    fprintf(fid,'			<vCodecDataSize type="int">0</>\n');
    fprintf(fid,'			<vFPS type="float">10</>\n');
    fprintf(fid,'			<vKeepDuration type="bool">T</>\n');
    fprintf(fid,'			<vBitRate type="int">0</>\n');
    fprintf(fid,'			<vBitRateMax type="int">0</>\n');
    fprintf(fid,'			<vBitRateMin type="int">0</>\n');
    fprintf(fid,'			<vKeyFrameRate type="int">0</>\n');
    fprintf(fid,'			<vQuality type="float">100</>\n');
    fprintf(fid,'			<vAsr type="int">0</>\n');
    fprintf(fid,'			<vDpiX type="int">0</>\n');
    fprintf(fid,'			<vDpiY type="int">0</>\n');
    fprintf(fid,'			<vOutResX type="int">640</>\n');
    fprintf(fid,'			<vOutResY type="int">480</>\n');
    fprintf(fid,'			<vOutBpp type="int">24</>\n');
    fprintf(fid,'			<vCodecName type="string">Cinepak#20Codec#20by#20Radius</>\n');
    fprintf(fid,'		</FileFormatFolder>\n');
    fprintf(fid,'	</Video>\n');
    fprintf(fid,'	<Audio>\n');
    fprintf(fid,'		<BlockVersion type="int">500</>\n');
    fprintf(fid,'		<FileName type="string">%s.gif</>\n',fullfile(movieDIR,strcat('fluctuation',bodyFN)));
    fprintf(fid,'		<SampleRateCustom type="bool">F</>\n');
    fprintf(fid,'		<SampleRate type="word">44100</>\n');
    fprintf(fid,'		<ChannelsCustom type="bool">F</>\n');
    fprintf(fid,'		<Channels type="word">2</>\n');
    fprintf(fid,'		<SampleResCustom type="bool">F</>\n');
    fprintf(fid,'		<SampleRes type="word">16</>\n');
    fprintf(fid,'		<AudioFormatInfo type="string">PCM,#20uncompressed</>\n');
    fprintf(fid,'		<FileFormatIndex type="int">0</>\n');
    fprintf(fid,'		<FileFormatFolder>\n');
    fprintf(fid,'			<aFileFmtId type="int">6</>\n');
    fprintf(fid,'			<aCodecId type="word">1</>\n');
    fprintf(fid,'			<aWaveFmtOut type="bin" size="18">0100020044AC000010B10200040010000000</>\n');
    fprintf(fid,'			<aBitRate type="word">0</>\n');
    fprintf(fid,'			<aQuality type="float">0</>\n');
    fprintf(fid,'			<aCodecName type="string">PCM,#20uncompressed</>\n');
    fprintf(fid,'		</FileFormatFolder>\n');
    fprintf(fid,'	</Audio>\n');
    fprintf(fid,'</OutputSettings>    \n');
else
    error('Undefined output format for VideoMach!!!\n');
end

end